# Generated by Django 4.1 on 2022-08-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('article_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('click_count', models.PositiveIntegerField()),
                ('register_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CrawledArticle',
            fields=[
                ('article_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('article_url', models.CharField(max_length=512, unique=True)),
                ('image_url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('register_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PvData',
            fields=[
                ('article_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('pv_count', models.PositiveIntegerField()),
                ('register_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendRelation',
            fields=[
                ('relation_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('originalArticle_id', models.PositiveIntegerField()),
                ('recommendArticle_id', models.PositiveIntegerField()),
                ('register_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
