# Generated by Django 4.1 on 2022-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_click_data_crawedarticle_pv_data_recommendrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawedarticle',
            name='article_url',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
