# Generated by Django 4.1 on 2022-08-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_crawedarticle_article_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pv_data',
            new_name='ClickData',
        ),
        migrations.RenameModel(
            old_name='click_data',
            new_name='PvData',
        ),
    ]
