# Generated by Django 4.1 on 2022-08-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_rename_pv_data_clickdata_rename_click_data_pvdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendrelation',
            old_name='recommandArticle_id',
            new_name='recommendArticle_id',
        ),
    ]
