# Generated by Django 4.1 on 2022-08-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_rename_recommandarticle_id_recommendrelation_recommendarticle_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crawedArticle',
            new_name='CrawledArticle',
        ),
    ]
