# Generated by Django 4.1 on 2022-08-29 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_rename_click_count_pvdata_pv_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendrelation',
            old_name='oroginalArticle_id',
            new_name='originalArticle_id',
        ),
    ]
