version: '3'
services:
    
  db:
    container_name: db
    build: ./mysql/    #Dockerfileからビルドすることを示す
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/DB:/docker-entrypoint-initdb.d  #初期データをマウントする場所
      - ./mysql/DB:/var/lib/mysql
    #image: original_mysql_world # イメージの名前
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'DB'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: django
      MYSQL_PASSWORD: django

  web:
    container_name: web
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    working_dir: /code
    ports:
      - 80:80
    volumes:
      - .:/code  #カレントディレクトリを/codeにマウントversion: '3'
        #depends_on:
        #- "db"
